component_depth: 1
languages:
- java
exclude:
- ./ant/.*
- ./bin/.*
- ./bin/com/.*
- ./bin/com/itextpdf/.*
- ./bin/com/itextpdf/rups/.*
- ./bin/com/itextpdf/rups/controller/.*
- ./bin/com/itextpdf/rups/io/.*
- ./bin/com/itextpdf/rups/io/filters/.*
- ./bin/com/itextpdf/rups/model/.*
- ./bin/com/itextpdf/rups/view/.*
- ./bin/com/itextpdf/rups/view/icons/.*
- ./bin/com/itextpdf/rups/view/itext/.*
- ./bin/com/itextpdf/rups/view/itext/treenodes/.*
- ./bin/com/itextpdf/rups/view/models/.*
- ./bin/com/itextpdf/text/.*
- ./bin/com/itextpdf/text/error_messages/.*
- ./bin/com/itextpdf/text/exceptions/.*
- ./bin/com/itextpdf/text/factories/.*
- ./bin/com/itextpdf/text/html/.*
- ./bin/com/itextpdf/text/html/simpleparser/.*
- ./bin/com/itextpdf/text/pdf/.*
- ./bin/com/itextpdf/text/pdf/codec/.*
- ./bin/com/itextpdf/text/pdf/codec/wmf/.*
- ./bin/com/itextpdf/text/pdf/collection/.*
- ./bin/com/itextpdf/text/pdf/crypto/.*
- ./bin/com/itextpdf/text/pdf/draw/.*
- ./bin/com/itextpdf/text/pdf/events/.*
- ./bin/com/itextpdf/text/pdf/fonts/.*
- ./bin/com/itextpdf/text/pdf/fonts/cmaps/.*
- ./bin/com/itextpdf/text/pdf/hyphenation/.*
- ./bin/com/itextpdf/text/pdf/interfaces/.*
- ./bin/com/itextpdf/text/pdf/internal/.*
- ./bin/com/itextpdf/text/pdf/parser/.*
- ./bin/com/itextpdf/text/pdf/qrcode/.*
- ./bin/com/itextpdf/text/pdf/richmedia/.*
- ./bin/com/itextpdf/text/xml/.*
- ./bin/com/itextpdf/text/xml/simpleparser/.*
- ./bin/com/itextpdf/text/xml/xmp/.*
- ./core/.*
- ./core/com/.*
- ./core/com/itextpdf/.*
- ./core/com/itextpdf/text/.*
- ./core/com/itextpdf/text/error_messages/.*
- ./core/com/itextpdf/text/exceptions/.*
- ./core/com/itextpdf/text/factories/.*
- ./core/com/itextpdf/text/html/.*
- ./core/com/itextpdf/text/html/simpleparser/.*
- ./core/com/itextpdf/text/pdf/.*
- ./core/com/itextpdf/text/pdf/codec/.*
- ./core/com/itextpdf/text/pdf/codec/wmf/.*
- ./core/com/itextpdf/text/pdf/collection/.*
- ./core/com/itextpdf/text/pdf/crypto/.*
- ./core/com/itextpdf/text/pdf/draw/.*
- ./core/com/itextpdf/text/pdf/events/.*
- ./core/com/itextpdf/text/pdf/fonts/.*
- ./core/com/itextpdf/text/pdf/fonts/cmaps/.*
- ./core/com/itextpdf/text/pdf/hyphenation/.*
- ./core/com/itextpdf/text/pdf/interfaces/.*
- ./core/com/itextpdf/text/pdf/internal/.*
- ./core/com/itextpdf/text/pdf/parser/.*
- ./core/com/itextpdf/text/pdf/qrcode/.*
- ./core/com/itextpdf/text/pdf/richmedia/.*
- ./core/com/itextpdf/text/xml/.*
- ./core/com/itextpdf/text/xml/simpleparser/.*
- ./core/com/itextpdf/text/xml/xmp/.*
- ./lib/.*
- ./rups/.*
- ./rups/com/.*
- ./rups/com/itextpdf/.*
- ./rups/com/itextpdf/rups/.*
- ./rups/com/itextpdf/rups/controller/.*
- ./rups/com/itextpdf/rups/io/.*
- ./rups/com/itextpdf/rups/io/filters/.*
- ./rups/com/itextpdf/rups/model/.*
- ./rups/com/itextpdf/rups/view/.*
- ./rups/com/itextpdf/rups/view/icons/.*
- ./rups/com/itextpdf/rups/view/itext/.*
- ./rups/com/itextpdf/rups/view/itext/treenodes/.*
- ./rups/com/itextpdf/rups/view/models/.*
